config/routes.rb
FbDemoApp::Application.routes.draw do
    resources :pages do
        member do
            get :following, :followers
        end
    end

    resources :albums
    resources :photos

    resources :pages, :only => [:show, :create, :destroy, :index, :new] do
        resources :albums, :only => [:show, :create, :destroy, :index, :new] do
            resources :photos, :only => [:show, :create, :destroy, :index, :new]
         end
     end

    resources :albums, :only => [:show, :create, :destroy, :index, :new] do
        resources :photos, :only => [:show, :create, :destroy, :index, :new]
    end

  resources :relationships, only: [:create, :destroy]
  
  root "pages#home"
  devise_for :users, :path => "/", :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }
  match 'users/:id'              , to: 'pages#show',      as:  'usershow', via: :get
  match 'auth/:provider/callback', to: 'sessions#create', via: :get
  match 'auth/failure',            to:  redirect('/'),    via: :get
  match 'signout',                 to: 'sessions#destroy', as: 'signout', via: :delete

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :user	
	has_many :photos, :dependent => :destroy 
	accepts_nested_attributes_for :photos, :allow_destroy => true
	validates :name, presence: true
	
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :album
	validates :pname, presence: true
	validates :purl,  presence: true
	has_attached_file :purl, :styles => { :small => "150x150" }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
	validates  :follower_id, presence: true
	validates  :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :relationships,  foreign_key: "follower_id",  dependent: :destroy
  has_many  :followed_users, through:     :relationships, source:    :followed

  has_many  :reverse_relationships,  foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many  :followers, through:     :reverse_relationships, source:    :follower
  
  has_many  :albums, dependent: :destroy

  validates :name,           presence: true
  validates :location,       presence: true
  has_attached_file :photo
  

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :fid)).first_or_initialize.tap do |user|
  		user.provider = auth.provider
  		user.fid = auth.uid
  		user.name = auth.info.name
      user.email = auth.info.email
      user.password = "password"
      user.location = auth.info.location
  		user.oauth_token = auth.credentials.token
  		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
  		user.save(:validates => false)
  	end
  end

  def to_param
    "#{id} #{name}".parameterize
  end

  def self.search(search)
    #search = "" unless search.present? 
    if search.present?
      # paginate :per_page => 12, :page => page, :conditions => ['name LIKE ?', "%#{search}%"]
        find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
      #where('name LIKE ?', "%#{search}%")
  
    else
       #paginate :per_page => 12, :page => page, :conditions => ['name LIKE ?', "%#{search}%"]
      find(:all)
    end
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def index
		@user = User.find(params[:page_id])
		if !user_signed_in?
			@albums = Album.where("user_id = ? AND scope = ?",params[:page_id], "Public")			

		elsif @user == current_user
			@albums = Album.where("user_id = ? ",params[:page_id])

		elsif (Relationship.find_by(follower_id: current_user.id,followed_id: @user.id) && Relationship.find_by(follower_id: @user.id,followed_id: current_user.id))
			@albums = Album.where("user_id = ? AND scope = ? OR scope = ?",params[:page_id], "Friends", "Public")
		end
	end

	def new
		@album = Album.new
		1.times { @album.photos.build }
	end

	def create
		@album = Album.new(albumParam)
		@album.user_id = current_user.id
		if @album.save
			flash[:notice] = "Successfully created Albums"
			redirect_to album_path(@album.id)
		else
			render :action => 'new'
		end
	end

	def show
		@album = Album.find(params[:id])
		@photos = @album.photos
	end

	private

		def albumParam
			params.require(:album).permit(:name, :description, :scope)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.  
	before_filter :configure_devise_params, if: :devise_controller?
  protect_from_forgery with: :exception    
  protected
    def configure_devise_params
    	devise_parameter_sanitizer.for(:sign_up) do 
    		|u| u.permit(:name, :location, :email, :password, :password_confirmation, :photo)
    	end
    	devise_parameter_sanitizer.for(:account_update) do
    		|u| u.permit(:name, :location, :email, :password, :password_confirmation, :current_password, :photo)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 def home
 	  #@users = User.page(params[:page])
  	#@users = User.search(params[:search]).page(params[:page])
  	@users = Kaminari.paginate_array(User.search(params[:search])).page(params[:page]).per(6)
  end

  def show
  	@user =  User.find(params[:id])
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    #@users = @user.followed_users
    @users = Kaminari.paginate_array(@user.followed_users).page(params[:page]).per(9)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = Kaminari.paginate_array(@user.followers).page(params[:page]).per(9)
    render 'show_follow'
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
		@user = User.find(params[:page_id])
		@album = Album.find(params[:album_id])			
		@photos = @album.photos.all
	end

	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.create(photoParam)
		@photo.album_id = params[:album_id]
		if @photo.save
			redirect_to album_path(@photo.album_id)
		else
			flash[:alert] = @photo.errors.full_messages
			redirect_to album_path(@photo.album_id)
		end
	end

	def show
		@photo = photo.find(params[:id])
	end
	
	def destroy
		@photo = Photo.find(params[:id])
		@photo.destroy;
		redirect_to album_path(@photo.album_id)
	end

	private

		def photoParam
			params.require(:photo).permit( :purl, :pname)
		end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
 def create
    @user = User.find(params[:user_id])
    current_user.follow!(@user)
    redirect_to page_path(@user)
  end

  def destroy
    @user = Relationship.find_by(followed_id: params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to page_path(@user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(env["omniauth.auth"])
		session[:user_id] = user.id 
		sign_in user
		redirect_to root_url
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/helpers/albums_helper.rb
module AlbumsHelper
	def Result?(current_user,user)
		Relationship.find_by(follower_id: current_user.follower_id,followed_id: user.followed_id) && Relationship.find_by(follower_id: user.follower_id,followed_id: current_user.followed_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Facebook "
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/albums/index.html.erb
<% provide(:title, 'index Page') %>
<h2>index Page</h2>

<div class="row">
  <div class="span6 offset3">
  	<% @albums.each do |album| %> 

	 	<ul class="list-group">
			 	<li class="list-group-item">
			 	
				  	<h4>Album Name&nbsp;&nbsp;&nbsp;
				  		<span class="label label-default">
				  			<%= label_tag album.name %>						
						</span>
					</h4><br />
					<h4>Description&nbsp;&nbsp;&nbsp;
			  			<span class="label label-default">
							<%= label_tag album.description %>
						</span>
					</h4><br />
			  		<h4>Scope&nbsp;&nbsp;&nbsp;
			  			<span class="label label-default">
							<%= label_tag album.scope %>
						</span>
					</h4><br />
					<center>
						<%= link_to "View Photos", page_album_photos_path(@user.id,album.id) %>
					</center>
				</li>
		</ul>
	<% end %>
		 
		<%#= render 'photos/photo_list' %>
	</div>
</div>

app/views/albums/new.html.erb
<% provide(:title, 'new Album') %>
<h2>New Album Page</h2>

<div class="row">
  <div class="span6 offset3">
	<%= form_tag albums_path, :method => :post , :html => { :multipart => true } do |f| %>
	 <%#= notice %>
		<ul class="list-group">	
		  	<li class="list-group-item">
			  	<h4>Album Name
			  		<span class="label label-default">
						<%= text_field_tag :name,"",:name => "album[name]" %>
					</span>
				</h4><br />
		  	</li>

		  	<li class="list-group-item">
		  		<h4>Description
		  			<span class="label label-default">
		  				<%= text_field_tag  :description,"",
		  				                    :name => "album[description]" %>
					</span>
				</h4><br />
		  	</li>

		  	 <li class="list-group-item">
		  		<h4>Scope
		  			<span class="label label-default">
		  				<%= select_tag :scope, options_for_select(%w[Public Friends Private]),:name => "album[scope]" %>
					</span>
				</h4><br />
		  	</li>
		  	<%= submit_tag "Create Album",  :class => "btn btn-primary btn-large " %>
		</ul>
	 <% end %>
	</div>
</div>

app/views/albums/show.html.erb
<% provide(:title, 'Album Page') %>
<h2>View Page</h2>

<div class="row">
  <div class="span6 offset3">
   	<%= form_for(Photo.new, :url => album_photos_path(@album.id), method: :post) do |f| %>
		<ul class="list-group">
		 	<li class="list-group-item">
			  	<h4>Album Name&nbsp;&nbsp;&nbsp;
			  		<span class="label label-default">
			  			<%= label_tag @album.name %>						
					</span>
				</h4><br />
				<h4>Description&nbsp;&nbsp;&nbsp;
		  			<span class="label label-default">
						<%= label_tag @album.description %>
					</span>
				</h4><br />
		  		<h4>Scope&nbsp;&nbsp;&nbsp;
		  			<span class="label label-default">
						<%= label_tag @album.scope %>
					</span>
				</h4><br />
		  	</li>
		  	<% if alert.present? %>
			 <div id="error_explanation">
			 	<div class="alert alert-error">
			  		<%= alert %>
	    		</div>
	    	</div>
	    	<% end %>
		  
		  	<li class="list-group-item">
		  		<h4>Photo Name&nbsp;&nbsp;&nbsp;
		  			<span class="label label-default">
						<%= f.text_field :pname %>
					</span>
				</h4><br />
		  	</li> 
		  	<li class="list-group-item">
		  		<h4>Photo Path&nbsp;&nbsp;&nbsp;
		  			<span class="label label-default">
						<%= f.file_field :purl %>
					</span>
				</h4><br />
		  	</li> 
		  	<%= f.submit "Add Photo",  :class => "btn btn-primary btn-large " %>
		</ul>

		<%= render 'photos/photo_list' %>
	<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer"> 
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to image_tag("fb.jpeg", alt: "Facebook"), 'https://facebook.com/' %>
      <nav>
        <ul class="nav pull-rightmy">
          <% if user_signed_in? %>
             Signed in as <b><%= current_user.email %>.</b>
            <%= link_to "Profile",  edit_user_registration_path %>
            <%= link_to "Create Albums",  new_album_path %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "Home", root_path %> or 
            <%= link_to "Sign up", new_user_registration_path %> or 
            <%= link_to "Sign in", new_user_session_path %>
            <%= link_to "FConnect", "/auth/facebook" , 
                id: "sign_in" %> 
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                            "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
   
  </head>
 <body>    
      <%= render 'layouts/header' %>
      <div class="container"> 
        <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="container"><hr>
<div class="row">
    <br/><br/><%= render 'shared/search' %>
    <div>     
        <div> 
            <center>
            <%= paginate @users, :theme => 'twitter-bootstrap-3', 
                :pagination_class => "pagination-lg" %>
            </center> 
        </div>
        <% @users.each do |user| %>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>
                            <%= link_to user.name, usershow_path(user) %>
                        </h3>
                    </div>
                    <div class="panel-body panelbodylead">
                        <b>Email Address :</b>
                        <%= user.email %><br>
                        <b>Location : </b>
                        <%= user.location %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>   

app/views/pages/show.html.erb
<% provide(:title, 'View Page') %>
<h2>View Page</h2>

<div class="row">
  <div class="span6 offset3">
	 <%= form_tag(remote: true) do |f| %>
		<ul class="list-group">
			<% if user_signed_in? %>
				<% if @user.photo.present? %>
					<li class="list-group-item">
				  	<h4>Profile Pic&nbsp;&nbsp;&nbsp;
				  		<span class="label label-default">
						 	<%= image_tag @user.photo.url %> 
						</span>
					</h4><br />
				  	</li>
			 	<% end %>
			<% end %>

		  	<li class="list-group-item">
			  	<h4>User Name&nbsp;&nbsp;&nbsp;
			  		<span class="label label-default">
						<%= label_tag @user.name %>
					</span>
				</h4><br />
		  	</li>

		  	<li class="list-group-item">
		  		<h4>Location&nbsp;&nbsp;&nbsp;
		  			<span class="label label-default">
						<%= label_tag @user.location %>
					</span>
				</h4><br />
		  	</li>
		  
		  	<li class="list-group-item">
		  		<h4>Email&nbsp;&nbsp;&nbsp;
		  			<span class="label label-default">
						<%= label_tag @user.email %>
						<%= label_tag @user.id %>
					</span>
				</h4><br />
		  	</li>
		  
		  	<li class="list-group-item">
		  		<h4><%= render 'shared/stats' %>
				</h4><br />
				<%= link_to "View Album",page_albums_path(@user.id) %>				
		  	</li>
		</ul>
	 <% end %>
	 <center>
	 	<% if user_signed_in? %>
			<%= render 'shared/follow_form' %>
		<% end %>
			<%= link_to "Back",root_url, class: "btn btn-large btn-primary" %>
	</center>
	<div>
		<% @user.followers.each do |follow| %>
			<% follow.followed_users.each do |followed| %>
		   		<% if followed == @user %>	
					<table class="table table-responsive">
						<tr>	
							<td class="active"><%=  follow.name %></td>	
							<td class="active"><%=  follow.email %></td>	
							<td class="active"><%=  follow.location %></td>	
						</tr>			
					</table>
				<% end %>
			<% end %>
		<% end %>
	</div>
   </div>
</div>

app/views/pages/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
   <div class="span8">
    <br/><br/>
   <div>
      <h2><%= @title %> of <%= @user.name %></h2>
      <centre>
        <%= paginate @users, :theme => 'twitter-bootstrap-3', 
            :pagination_class => "pagination-lg" %>
        <%= link_to "Back", usershow_path(@user) %>
      </centre>
    </div>
    <% if @users.any? %>
      <ul class="users">
        <% @users.each do |user| %>
          <div class="col-md-5">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h3>
                  <%= link_to user.name , usershow_path(user) %>
                </h3>
              </div>
              <div class="panel-body panelbodylead">
                <b>Email :</b>
                <%= user.email %><br>
                <b>Location : </b>
                <%= user.location %>
              </div>
            </div>
          </div>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/photos/_photo_list.html.erb
<div class="row">
<% @photos.each do |photo| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
         <center><b><%= photo.pname %></b></center>
        <%= image_tag photo.purl %>
        <div class="caption">
       <center><%= link_to "Remove", album_photo_path(@album.id,photo.id) , method: :delete, :class => "btn btn-danger btn-small" %> 
       </center>
        </div>
    </div>
  </div>
<% end %>
</div>

app/views/photos/index.html.erb
<div class="row">
  <br/><br/><br/><br/>
  <center>
     <ol class="breadcrumb">
      <li>User</a></li>
      <li>Albums</a></li>
      <li class="active">Photos</li>
    </ol>
  </center>
  <% @album.photos.each do |photo| %> 
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
          <center>
            <b><%= photo.pname %></b>
          </center>       
          <div class="caption">
            <%= image_tag photo.purl %>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_follow.html.erb
<%= form_for(current_user.relationships.new, url: relationships_path(:user_id =>
	@user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_follow_form.html.erb
<% unless current_user==@user %>
	<% if current_user.following?(@user) %>
		<%= render 'shared/unfollow' %>
	<% else %>
		<%= render 'shared/follow' %>
	<% end %>
<% end %>

app/views/shared/_search.html.erb
<div class="row">
	<div class="span6 offset3">
    <%= form_tag root_url, :method => 'get' do %>
       	<center> <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "submit", :name => nil %>
        </p></center>
    <% end %>
	</div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_page_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_page_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_unfollow.html.erb
<%= form_for(@user, url: relationship_path(@user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>